CREATE TABLE PETSHOPREQ (
    SERVICO VARCHAR(20),
    ANIMAL VARCHAR(20),
    MARCA VARCHAR(20),
    QUANTIDADE VARCHAR(20),
    MEDICAMENTOS VARCHAR(20),
    BRINQUEDOS VARCHAR(20),
    PRECO VARCHAR(20)
)


SELECT * FROM RACAO WHERE SERVICO = 'Ração' AND MARCA = 'Golden' AND QUANTIDADE = '1 kg' AND ANIMAL = 'Gato'

SELECT * FROM RACAO